//! Final encode-parse-equality proof for generated catalog artifacts.

use crate::catalog::{CatalogArtifact, CatalogIssue};

pub(super) fn validate(artifact: &CatalogArtifact) -> Result<CatalogArtifact, CatalogIssue> {
    let mut body = Vec::new();
    artifact
        .write_pretty(&mut body)
        .map_err(|error| generated(error.to_string()))?;
    let parsed = CatalogArtifact::from_slice(&body)
        .map_err(|error| generated(format!("bounded parser rejected generated bytes: {error}")))?;
    if &parsed != artifact {
        return Err(generated(
            "bounded parser changed generated artifact semantics".to_owned(),
        ));
    }
    Ok(parsed)
}

fn generated(reason: String) -> CatalogIssue {
    CatalogIssue::InvalidGeneratedArtifact { reason }
}
